name: Move new issues into Triage

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - name: create card
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Bug triage
          column: Requires Investigation
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
      - name: Comment issue
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GHPROJECT_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for your reporting a bug."
            })
